### ISSUE TITLE
License About this model

### ISSUE THREAD

**Issue by jeungmin717** [MareArts/MareArts-ANPR#1]
I want to know which license this repository use

**Comment by MareArts** [comment]
Hi, sorry for late answer.
I just found your message now.
You can buy license key by 1 year subscription.
Here is page you can purchase : https://study.marearts.com/p/anpr-lpr-solution.html
You can also test SDK through public key but in case of public key ANPR process works on server side so it can be slower (upload -> process -> download) than normal license. 
Thank you. 🙏

**Comment by MareArts** [comment]
I would like to close this issue, if you don't have further question.
